name: Validate

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install  --no-root -v
      - name: Analysing the code
        run: |
          poetry run black --line-length=180 --check .
          poetry run mypy --ignore-missing-imports .
          poetry run flake8 --max-line-length=180 .
      - name: Run tests
        run: |
          poetry run coverage run --source=pipeline  -m unittest discover -s ./tests -p test_*.py
          poetry run coverage report
